### ISSUE TITLE
[Hoster Request] VOE / UPStream

### ISSUE THREAD

**Issue by Vojovnik** [DATL4G/BurningSeries-Android#12]
Hi!

Videos lassen sich nicht über den Hoster VOE, oder UPStream starten. Es erscheint ständig die Meldung "Stream nicht verfügbar". Tatsächlich lässt sich der Stream aber via Browser öffnen.

Das funktioniert nur leider an meinem TV nur mit angeschlossener Tastatur. 
Bei den meisten Serien ist man leider auf VOE angewiesen, v.a. bei älteren.

Könntest du dir das anschauen?

**Comment by stella1407** [comment]
Ja habe ich schon bemerkt Dankeschön für den Hinweis ich kenne mich hier
überhaupt nicht aus und weiss auch nicht wie das hier alles funktioniert
weil ich kein Englisch kann

Vojovnik ***@***.***> schrieb am Di., 25. Okt. 2022, 01:06:

**Comment by Vojovnik** [comment]
java.lang.RuntimeException: Parcel android.os.Parcel@16a1591: Unmarshalling unknown type code 3211300 at offset 3444
	at android.os.Parcel.readValue(Parcel.java:3318)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3719)
	at android.os.Parcel.readSparseArray(Parcel.java:2857)
	at android.os.Parcel.readValue(Parcel.java:3296)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3636)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2270)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1768)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1721)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1376)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4152)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by DATL4G** [comment]
@Vojovnik 

Hey ich seh mir das mal an.

Und beachte @stella1407 einfach nicht, er/sie ist kein Maintainer, hat das nicht programmiert, und versteht anscheinend nicht wie GitHub funktioniert.
Also auf seine/ihre Anfragen und Antworten brauchst du gar nicht erst reagieren.

**Comment by DATL4G** [comment]
@Vojovnik 

Kannst du mir noch sagen welche Serie, Staffel und Folge z.B. nicht geht

Brauche nur eine damit ich das schneller finden und testen kann

**Comment by Vojovnik** [comment]
Getestet habe ich das übrigens mit zwei unterschiedlicher VPN-Clients an zwei verschiedenen an zwei unterschiedlichen Androidgeräten (mit unterschiedlichen Android-Versionen) an jeweils einem Telekom Speedport und einem Fritzrepeater (wobei letzteres irrelevant sein müsste wegen VPN)

**Comment by stella1407** [comment]
Ich schaue gerne chicago fire und manchmal funktioniert es und manchmal
nicht

Vojovnik ***@***.***> schrieb am Di., 25. Okt. 2022, 14:43:

**Comment by DATL4G** [comment]
@Vojovnik 

Fehler behoben mit der neuen [Version](https://github.com/DATL4G/BurningSeries-Android/releases/tag/v3.2.0)

Viel Spaß :)

**Comment by stella1407** [comment]
Thank you!

DatLag ***@***.***> schrieb am Di., 25. Okt. 2022, 21:48:
