### ISSUE TITLE
[BUG] Some Hosters still aren't working

### ISSUE THREAD

**Issue by Regesch** [DATL4G/BurningSeries-Android#13]
I habe die Version 3.2.1 auf meinem Gerät installiert und habe versucht Cosmo und Wanda zu schauen, doch es ging leider nicht. Obwohl die erste Folge auch über den Hoster VOE geschaut werden konnte, wurde mir angezeigt, dass kein Hoster verfügbar ist.

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.util.regex.Matcher.appendEvaluated(Matcher.java:737)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:717)
	at android.support.v4.media.a.Y0(Unknown Source:29)
	at b7.b.a(SourceFile:27)
	at b7.b$a.invoke(Unknown Source:26)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy11.b(Unknown Source)
	at u3.e.get(Unknown Source:38)
	at b7.p.e(SourceFile:1)
	at b7.p.b(SourceFile:10)
	at de.datlag.burningseries.ui.fragment.SettingsFragment$loadUserImage$1.v(SourceFile:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.l(Unknown Source:8)
	at ja.e0.run(Unknown Source:100)
	at oa.e.run(Unknown Source:12)
	at pa.h.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$a.run(SourceFile:85)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [i1{Cancelling}@2ea4862, Dispatchers.IO]

**Comment by Regesch** [comment]
Alles klar hat sich erledigt. Ich habe nämlich nicht gewusst, dass man bei manchen Folgen den Link selber noch verknüpfen muss.
