### ISSUE TITLE
[BUG] Hoster StreamZZ Not working

### ISSUE THREAD

**Issue by Regesch** [DATL4G/BurningSeries-Android#14]
Sadly, the Hoster StreamZZ isn't working. I tried to activate the Link for the First Episode of Jujutsu Kaisen and when the Stream was about to get started, it failed because it says that the Stream isn't available but you can Stream it whencyou are on an Internet Browser, so the File isn't deleted from that hoster.

java.lang.RuntimeException: Parcel android.os.Parcel@aca6508: Unmarshalling unknown type code 6881391 at offset 2968
	at android.os.Parcel.readValue(Parcel.java:3321)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3726)
	at android.os.Parcel.readSparseArray(Parcel.java:2860)
	at android.os.Parcel.readValue(Parcel.java:3299)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3643)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2219)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1740)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1693)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1391)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3821)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by DatL4g** [comment]
Will be fixed in the new version 4.0.0
