### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Phossi** [DATL4G/BurningSeries-Android#4]
**Describe the bug**
The search screen shows no output, it just loads infinitely.
Even without a search-phrase it shows nothing.

**To Reproduce**
1. Go to 'Mehr...'

**Expected behavior**
It should show some results

**Screenshots**
![image](https://user-images.githubusercontent.com/53015987/175527018-de992db3-a999-4c6d-9c37-d7f37bc67af8.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 11
 - Version: 3.0.0

**Additional context**
Stack trace of the latest error:
java.lang.IllegalArgumentException: Unable to create converter for java.util.List<de.datlag.model.burningseries.allseries.GenreModel$GenreData>
    for method a.d
	at retrofit2.b.j(SourceFile:2)
	at rb.t.b(SourceFile:79)
	at rb.s.c(Unknown Source:24)
	at rb.s$a.invoke(Unknown Source:37)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.d(Unknown Source)
	at de.datlag.network.burningseries.BurningSeriesRepository$getAllSeries$1$invokeSuspend$$inlined$networkBoundResource$default$1.w(SourceFile:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.m(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.SafeCollector.w(Unknown Source:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.m(Unknown Source:8)
	at kotlinx.coroutines.flow.internal.SafeCollector.w(Unknown Source:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.m(Unknown Source:8)
	at ba.f0.run(Unknown Source:86)
	at ga.e.run(Unknown Source:12)
	at ha.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$a.run(SourceFile:9)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [i1{Cancelling}@ad32228, [Dispatchers.IO](http://dispatchers.io/)]
Caused by: kotlinx.serialization.SerializationException: Serializer for class 'GenreData' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at w.c.c0(SourceFile:4)
	at i6.e.q1(SourceFile:12)
	at w.c.c0(SourceFile:1)
	at u6.b.b(SourceFile:1)
	at rb.s.e(Unknown Source:36)
	at rb.t.b(SourceFile:77)
	... 14 more

**Comment by DATL4G** [comment]
This is weird as I don't face this problem on any of my devices.

However since the error log (thanks for providing this) says it cannot create a converter for the class, the origin of this problem is probably sealed classes. (This is the only way it works for me but not for you)
I will change it to independent classes and I'll try to resolve the issue.

**Comment by DATL4G** [comment]
Fixed and new version available: https://github.com/DATL4G/BurningSeries-Android/releases/tag/v3.0.1
