### ISSUE TITLE
VLC Player is not being recognised by the application

### ISSUE THREAD

**Issue by ghost** [DATL4G/BurningSeries-Android#56]
**Describe the bug**
The bug is that: Whenever I start an episode in the desktop app, it displays that VLC has to be installed in order to run the
episode, although the latest version is already installed on my device.

**To Reproduce**
1. Open the application
2. Open any activated episode
3. See error

**Expected behavior**
Normally it should just run the episode I guess, just as it does on the mobile version or on the website.

**Screenshots**
![image](https://github.com/DATL4G/Burning-Series/assets/127989016/523baab3-6ebd-402b-bbbe-2f147013d1d1)

![image](https://github.com/DATL4G/Burning-Series/assets/127989016/443dc096-5f45-484e-8d02-ffe8e7e676ca)

**Smartphone (please complete the following information):**
 - Device: Lenovo IdeaPad S145 (2020)
 - OS: Windows 10
 - Version [4.7.0]

**Additional context**

java.lang.IllegalStateException: Configurations must be unique
	at com.arkivanov.decompose.router.children.ChildrenNavigator.switch(ChildrenNavigator.kt:115)
	at com.arkivanov.decompose.router.children.ChildrenNavigator.navigate(ChildrenNavigator.kt:109)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(ChildrenFactory.kt:128)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(ChildrenFactory.kt:125)
	at com.arkivanov.decompose.Relay$queue$1.invoke(Relay.kt:13)
	at com.arkivanov.decompose.Relay$queue$1.invoke(Relay.kt:12)
	at com.arkivanov.decompose.SerializedQueue.drain(SerializedQueue.kt:23)
	at com.arkivanov.decompose.SerializedQueue.offer(SerializedQueue.kt:17)
	at com.arkivanov.decompose.Relay.accept(Relay.kt:25)
	at com.arkivanov.decompose.router.stack.DefaultStackNavigation.navigate(DefaultStackNavigation.kt:11)
	at com.arkivanov.decompose.router.stack.StackNavigatorExtKt.push(StackNavigatorExt.kt:16)
	at com.arkivanov.decompose.router.stack.StackNavigatorExtKt.push$default(StackNavigatorExt.kt:15)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent.onEpisodeClicked(NavHostComponent.kt:164)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent.access$onEpisodeClicked(NavHostComponent.kt:41)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent$createScreenComponent$4.invoke(NavHostComponent.kt:87)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent$createScreenComponent$4.invoke(NavHostComponent.kt:87)
	at dev.datlag.burningseries.ui.screen.series.SeriesScreenComponent$loadEpisode$1$2.invokeSuspend(SeriesScreenComponent.kt:260)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@73491c04, Dispatchers.IO]

**Comment by DatL4g** [comment]
Please check https://github.com/DATL4G/Burning-Series/discussions/57

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
