### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TILGAMER** [DATL4G/BurningSeries-Android#59]
It's red in the settings and said to add this to bug report

java.lang.IllegalStateException: Session ID must be unique. ID=
	at androidx.media3.session.MediaSession.<init>(MediaSession.java:552)
	at androidx.media3.session.MediaSession$Builder.build(MediaSession.java:359)
	at dev.datlag.burningseries.ui.screen.video.VideoPlayerKt.VideoPlayer(VideoPlayer.kt:168)
	at dev.datlag.burningseries.ui.screen.video.VideoScreenKt.VideoScreen(VideoScreen.kt:15)
	at dev.datlag.burningseries.ui.screen.video.VideoScreenComponent.render(VideoScreenComponent.kt:243)
	at dev.datlag.burningseries.ui.navigation.ComposableSingletons$NavHostComponentKt$lambda-1$1.invoke(NavHostComponent.kt:208)
	at dev.datlag.burningseries.ui.navigation.ComposableSingletons$NavHostComponentKt$lambda-1$1.invoke(NavHostComponent.kt:207)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1$1.invoke(Children.kt:31)
	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1$1.invoke(Children.kt:30)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1.invoke(Children.kt:30)
	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1.invoke(Children.kt:29)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.DefaultStackAnimation$Item$childContent$1$1.invoke(DefaultStackAnimation.kt:71)
	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.DefaultStackAnimation$Item$childContent$1$1.invoke(DefaultStackAnimation.kt:69)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ComposerImpl$invokeMovableContentLambda$1.invoke(Composer.kt:2947)
	at androidx.compose.runtime.ComposerImpl$invokeMovableContentLambda$1.invoke(Composer.kt:2947)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
	at androidx.compose.runtime.ComposerImpl.invokeMovableContentLambda(Composer.kt:2947)
	at androidx.compose.runtime.ComposerImpl.access$invokeMovableContentLambda(Composer.kt:1230)
	at androidx.compose.runtime.ComposerImpl$insertMovableContentGuarded$1$1$2$1.invoke(Composer.kt:3067)
	at androidx.compose.runtime.ComposerImpl$insertMovableContentGuarded$1$1$2$1.invoke(Composer.kt:3064)
	at androidx.compose.runtime.ComposerImpl.recomposeMovableContent(Composer.kt:3236)
	at androidx.compose.runtime.ComposerImpl.recomposeMovableContent$default(Composer.kt:3213)
	at androidx.compose.runtime.ComposerImpl.insertMovableContentGuarded(Composer.kt:3064)
	at androidx.compose.runtime.ComposerImpl.insertMovableContentReferences(Composer.kt:2964)
	at androidx.compose.runtime.CompositionImpl.insertMovableContent(Composition.kt:785)
	at androidx.compose.runtime.Recomposer.performInsertValues(Recomposer.kt:1068)
	at androidx.compose.runtime.Recomposer.access$performInsertValues(Recomposer.kt:124)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:574)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1158)
	at android.view.Choreographer.doCallbacks(Choreographer.java:950)
	at android.view.Choreographer.doFrame(Choreographer.java:874)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@724ea88, androidx.compose.ui.platform.MotionDurationScaleImpl@75d7c21, StandaloneCoroutine{Cancelling}@1261846, AndroidUiDispatcher@4c1da07]

Builder.build, CallbackRecord.run, FrameDisplayEventReceiver.run, MethodAndArgsCaller.run

It should be blue

Poco X3 NFC
Android 12 and MIUI 14.0.4
![Screenshot_2023-08-02-15-55-33-654-edit_dev datlag burningseries](https://github.com/DATL4G/Burning-Series/assets/141247386/de49514e-bfed-46d6-9017-e257c00b115f)

**Additional context**

**Comment by TrueMadMotion** [comment]
`java.lang.IllegalStateException: Check failed.
	at androidx.compose.ui.focus.FocusTargetModifierNode.fetchFocusProperties$ui_release(FocusTargetModifierNode.kt:141)
	at androidx.compose.ui.focus.TwoDimensionalFocusSearchKt.collectAccessibleChildren(TwoDimensionalFocusSearch.kt:216)
	at androidx.compose.ui.focus.TwoDimensionalFocusSearchKt.findChildCorrespondingToFocusEnter--OM-vw8(TwoDimensionalFocusSearch.kt:121)
	at androidx.compose.ui.focus.FocusTransactionsKt.requestFocus(FocusTransactions.kt:41)
	at androidx.compose.ui.focus.FocusRequester$requestFocus$1.invoke(FocusRequester.kt:66)
	at androidx.compose.ui.focus.FocusRequester$requestFocus$1.invoke(FocusRequester.kt:66)
	at androidx.compose.ui.focus.FocusRequester.findFocusTarget$ui_release(FocusRequester.kt:86)
	at androidx.compose.ui.focus.FocusRequester.requestFocus(FocusRequester.kt:66)
	at dev.datlag.burningseries.ui.screen.genre.GenreScreenAppBarKt$GenreScreenAppBar$5$1.invoke(GenreScreenAppBar.kt:59)
	at dev.datlag.burningseries.ui.screen.genre.GenreScreenAppBarKt$GenreScreenAppBar$5$1.invoke(GenreScreenAppBar.kt:59)
	at dev.datlag.burningseries.ui.custom.SearchAppBarKt$SearchAppBar$1$2$1.invoke(SearchAppBar.kt:93)
	at dev.datlag.burningseries.ui.custom.SearchAppBarKt$SearchAppBar$1$2$1.invoke(SearchAppBar.kt:92)
	at androidx.compose.foundation.text.KeyboardActionRunner.runAction-KlQnJC8(KeyboardActionRunner.kt:68)
	at androidx.compose.foundation.text.TextFieldState$onImeActionPerformed$1.invoke-KlQnJC8(CoreTextField.kt:854)
	at androidx.compose.foundation.text.TextFieldState$onImeActionPerformed$1.invoke(CoreTextField.kt:853)
	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onImeAction-KlQnJC8(TextInputServiceAndroid.android.kt:132)
	at androidx.compose.ui.text.input.RecordingInputConnection.performEditorAction(RecordingInputConnection.android.kt:336)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$performEditorAction$21$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:654)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda33.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
`

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
