### ISSUE TITLE
[BUG] Saving failed

### ISSUE THREAD

**Issue by ngelus** [DATL4G/BurningSeries-Android#60]
**Describe the bug**
Getting a lot of "saving failed" messages after activating episodes recently.

**To Reproduce**
1. Go to any series.
2. Click on any episode.
3. Solve the captcha.
4. Receive error message "saving failed.

**Expected behavior**
It should save the episodes. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 13
 - Version: latest (v4.7.0)

**Additional context**
I don't know if maybe your server is unreachable, but I've also been prompted to activate more often recently.

**Logs:**
```
java.lang.IllegalStateException: Configurations must be unique
	at com.arkivanov.decompose.router.children.ChildrenNavigator.switch(ChildrenNavigator.kt:115)
	at com.arkivanov.decompose.router.children.ChildrenNavigator.navigate(ChildrenNavigator.kt:109)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(ChildrenFactory.kt:128)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(ChildrenFactory.kt:125)
	at com.arkivanov.decompose.Relay$queue$1.invoke(Relay.kt:13)
	at com.arkivanov.decompose.Relay$queue$1.invoke(Relay.kt:12)
	at com.arkivanov.decompose.SerializedQueue.drain(SerializedQueue.kt:23)
	at com.arkivanov.decompose.SerializedQueue.offer(SerializedQueue.kt:17)
	at com.arkivanov.decompose.Relay.accept(Relay.kt:25)
	at com.arkivanov.decompose.router.stack.DefaultStackNavigation.navigate(DefaultStackNavigation.kt:11)
	at com.arkivanov.decompose.router.stack.StackNavigatorExtKt.push(StackNavigatorExt.kt:16)
	at com.arkivanov.decompose.router.stack.StackNavigatorExtKt.push$default(StackNavigatorExt.kt:15)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent.onEpisodeClicked(NavHostComponent.kt:164)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent.access$onEpisodeClicked(NavHostComponent.kt:41)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent$createScreenComponent$4.invoke(NavHostComponent.kt:87)
	at dev.datlag.burningseries.ui.navigation.NavHostComponent$createScreenComponent$4.invoke(NavHostComponent.kt:87)
	at dev.datlag.burningseries.ui.screen.series.SeriesScreenComponent$loadEpisode$1$2.invokeSuspend(SeriesScreenComponent.kt:260)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d2183c1, Dispatchers.IO]
```

**Comment by Araska90** [comment]
Same issue

**Comment by ngelus** [comment]
@DATL4G did ya abandon this project? 😣

**Comment by DatL4g** [comment]
@ngelus the project isn't abandoned, but I currently have no time to work on this because of personal problems

**Comment by DatL4g** [comment]
There is some trouble with the server host but, there is a backup solution already implemented in the latest version, sometimes you just have to click the episode again to get it loading

**Comment by ngelus** [comment]
Ah. Perfect.

**Comment by DatL4g** [comment]
https://github.com/DatL4g/Burning-Series/issues/62
